### PR TITLE
Add Bill St. Clair

### PR DESCRIPTION
**Pull request by billstclair**

### CODE REVIEW

**Comment by Hexstream** [comment]
Thank you very much for this add request!

I haven't yet started reviewing it, I'm trying to figure out how to checkout your branch directly into a branch on my private repo, so that I can then use my usual workflows and make sure everything is proper. (I'm not very used to collaboration, I usually "program in a corner".)

Hopefully I can get back to you today!

**Comment by billstclair** [comment]
This may help: https://stackoverflow.com/a/38985999

**Comment by Hexstream** [comment]
That's good to know, but not exactly what I want to do.

I do not want to successfully merge your pull request into another branch, I just want to "import" your branch locally in my private repo so that I can use my usual workflows to review your add request, if everything is perfect I would then push your commit directly to my master branch.

**edit:** I could instead clone your repo, review your changes and then add my repo as a remote and push from the clone, which I already know how to do, but I would like to avoid the extra steps now and in the future.

**Comment by svetlyak40wt** [comment]
Jean, you can use a [hub](https://hub.github.com) wrapper around github, with it you'll be able to checkout directly a pull request like:

```
hub pr checkout 3
```

**Comment by billstclair** [comment]
Ah, in that case, you want to pull my fork into a copy of your repository,
test it, push, and then pull back into the usual copy of your repository.
Something like:

$ mkdir .../tmp
$ cd .../tmp
$ git clone git@github.com:Hexstream/common-lispers.hexstreamsoft.com.git
$ cd common-lispers.hexstreamsoft.com
$ git pull git@github.com:billstclair/common-lispers.hexstreamsoft.com.git
$
# Do testing
# If all looks good:
$ git push
# Then change to your normal repository
$ cd .../common-lispers.hexstreamsoft.com
$ git pull
# and delete the temporary directory
$ rm -r .../tmp

**Comment by Hexstream** [comment]
Ok, I did:

```
git remote add bill https://github.com/billstclair/common-lispers.hexstreamsoft.com.git
git fetch bill
git checkout -b bill bill/master
```

I was looking for something a bit more direct, something like:

```
git checkout -b bill https://github.com/billstclair/common-lispers.hexstreamsoft.com.git/master
```

What I did is satisfactory, for now.

**Comment by Hexstream** [comment]
@svetlyak40wt I'm pretty conservative about trying new tools, maybe I should investigate `hub` sometime...

**edit:** `hub` does look pretty useful and worth the investment! Thanks!

**Comment by Hexstream** [comment]
Ok, I can see that there are inconsistencies between your entry and how I have been doing things for all other entries. This is due to the policies page not yet reflecting the rules I've been following accurately enough.

My brothers are visiting, so I'll probably only have time to analyze this fully tomorrow.

Thank you for your patience!

**Comment by billstclair** [comment]
I attempted to duplicate other entries, and follow the policies. Anyway,
feel free to use my pull request as a template, and fix it as necessary. Or
send me the changes, and I'll fix it in a new commit. Whichever you like.

**Comment by Hexstream** [comment]
I appreciate your efforts.

It is less work for me and the requestor if I just create the commit myself, but I want to give requestors the opportunity to get their own commit pushed if they wish. But this would generally involve multiple rounds of reviews and polishing to get the commit to a suitable state.

I would rather avoid just merging their slightly wrong commit and then immediately adding another commit to fix up things, as that results in a much uglier git history.

So generally, requestors would have to decide if they want to go to the extra hassle of making their own commit so that I can push that directly, or if they want to let me create the commit. In this early stage, I would generally recommend the latter option.

As the policies become more fleshed out and clearer, and as the community gains experience in adding people to the list, it should become more and more feasible for requestors to create the commit without endless rounds of polishing.

I thank you for going through the effort of participating in this project at this early stage!

**Comment by Hexstream** [comment]
Sorry, there has been a slight change of plans, so I won't be able to process your add request today, after all. I apologize.

There are two reasons for this, the first one is that today I have had some pretty great ideas for a major update to the policies, which it would be in the interests of the project to implement as soon as possible. Compounding this, today I learned that the [ELS](https://www.european-lisp-symposium.org/2019/index.html) will be taking place beginning tomorrow. (I had thought it was around April 4, I don't generally pay attention to conferences.)

I expect that there would be at least some background chatter about the Common Lispers list at that conference, and it would be great if I could push out some updates to the policies in time, although that is indeed a very tight deadline. We'll see how that goes...

**So, I will be temporarily putting all add requests on hold.** This shouldn't last too long. I apologize for the inconvenience. People are free to continue to submit add requests if they want to reserve their place in line, while keeping in mind that they may subsequently have to amend their requests according to the updated policies.

Thank you for your understanding!

**Comment by billstclair** [comment]
No problem from my perspective. You're providing a service here. You owe me nothing. Thank you!

**Comment by Hexstream** [comment]
Alright! I was finally able to process your add request today.

[Your entry is live!](https://common-lispers.hexstreamsoft.com/#Bill_St_Clair)

I had to make a few changes to your entry compared to the one in your pull request, to ensure [consistency](https://common-lispers.hexstreamsoft.com/policies/#tenets_consistency) with all other entries.

I hope this is to your satisfaction!

**Comment by billstclair** [comment]
Looks great. Thank you for creating the site.

**Comment by Hexstream** [comment]
Awesome! Thank you very much!

On launch day, just before going to bed, I saw that someone had immediately requested to be removed, and nobody had requested to be added yet, so I was a bit worried and thought I might face a wave of further removal requests the day after, with little other interest.

Your add request in particular was very reassuring and validating! :heart:

**Pull request closed without merging**
