### PR TITLE
fix typos

### PR DESCRIPTION
**Pull request by adlai**

### CODE REVIEW

**Comment by Hexstream** [comment]
Oops, good catch, I had forgotten about the CSS file.

Unfortunately, you forgot to change the `id="footnote_diseased-persons"` in this second pull request.

(I quickly found this by going in the emacs dired for the repo and invoking `M-x grep-find diseased RET`.)

Fortunately, that's easy to fix. Just ensure that you are in the correct branch, then make the small fix, then invoke `git commit --amend -aC HEAD` then `git push -f origin` to update your pull request in-place.

We're almost there!

**Comment by Hexstream** [comment]
Thank you for the report! It has been 3 days since our last interaction and I was eager to finally fix this embarrassing typo, so I made my own commit to spare us any further delays.

I credited you in the [commit message](https://github.com/Hexstream/common-lispers.hexstreamsoft.com/commit/d03f39e54e9c15c4f2a02dae2f722318fd560540). I hope this is to your satisfaction.

**Comment by adlai** [comment]
@Hexstream [wrote](https://github.com/Hexstream/common-lispers.hexstreamsoft.com/pull/7#issuecomment-479111560)
> I credited you in the commit message. I hope this is to your satisfaction.

Indeed it is!

**Comment by Hexstream** [comment]
Thank you for the confirmation!

**Pull request closed without merging**
